# config/meta.yml

meta_product_name: "Happy Vita"
meta_title: "Happy Vita - Por uma vida mais ativa"
meta_description: "Encontre atividades que combinem com vocÃª."
meta_image: "fbcover.png" # should exist in `app/assets/images/`
twitter_account: "@_brsystems"   # required for Twitter Cards